### ISSUE TITLE
It appears that Math::libm fails on ARM macbooks maybe

### ISSUE THREAD

**Issue by dr-kd** [ology/Groove-Tool#1]
as title

**Comment by dr-kd** [comment]
nope, just failing tests on my mac

**Comment by dr-kd** [comment]
aah it's a math::libm install problem - so it looks like this may not be ok on OS x.

**Comment by ology** [comment]
@singingfish This mojo tool installs and runs (with morbo) fine on my ancient High Sierra MacBook Pro version 10.13.6 with perl v5.30.2. And Math::libm installed without a hitch too.

**Comment by ology** [comment]
Yep. Got a friend to try with his ARM machine, and it failed on Math::libm too. Aaaaaaaa!

**Comment by ology** [comment]
Ok! I have removed the dependency on Math::libm in my Music::CreatingRhythms repo, and made the GrooveTool cpanfile specify versions.

Thank you **so much** for this report. I did not realize there was an issue with ARM vs that module.

**Comment by dr-kd** [comment]
Not on intel - looks like some of my problem is latest os x is perl 5.30 and there are upstream dependencies on 5.32 - I'll try to get to installing with perlbrew over the next few days
